### ISSUE TITLE
Black list

### ISSUE THREAD

**Issue by yardenmatok203** [calico/basenji#174]
Hey,

can you share your blacklist which indicates which areas in the genome are problematic for prediction?

Thanks,
Yarden.

**Comment by davek44** [comment]
Sure...
Blacklist: https://storage.googleapis.com/basenji_barnyard2/hg38.blacklist.rep.bed
Unmappable: https://storage.googleapis.com/basenji_barnyard2/umap_k36_t10_l32_hg38.bed

**Comment by yardenmatok203** [comment]
what is "Unmappable"?

thanks,
Yarden

**Comment by davek44** [comment]
Unmappable specifies regions that are particularly difficult to map short reads to due to repeats.

**Comment by yardenmatok203** [comment]
How should I use this mapping regions for prediction with your weights? For
hff for example?
How did you use those areas in training?


Thank you,
Yarden

בתאריך יום ב׳, 14 באוג׳ 2023, 23:18, מאת David Kelley ‏<
***@***.***>:

**Comment by yardenmatok203** [comment]
Hey David,

one more question, does: data/hg38_gaps_binsize2048_numconseq10.bed , handle this blacklist?

Thanks,
Yarden

**Comment by davek44** [comment]
Hi Yarden, I'm not sure I understand your questions. I don't recognize the filename you sent. You can choose to handle regions of difficult mappability however you'd like; there's no right or wrong way. I typically have the program clip the values in unmappable regions so that they aren't allowed to be very large.
