### ISSUE TITLE
Issue in running bam_cov.py

### ISSUE THREAD

**Issue by kiranvpaul** [calico/basenji#23]
Hello,
I was trying to run preprocess step in which when i am running bam_cov.py and it is giving a key error 'HG19'

The command iam giving is bam_cov.py FLAG-MSI2_2_iCLIP.bam FLAG-MSI2_2.bw

the error message i am getting is
Traceback (most recent call last):
  File "/ysm-gpfs/home/kvp6/Kiran.vp/Tools/basenji-master/bin/bam_cov.py", line 1631, in <module>
    main()
  File "/ysm-gpfs/home/kvp6/Kiran.vp/Tools/basenji-master/bin/bam_cov.py", line 95, in main
    default='%s/assembly/hg19.fa' % os.environ['HG19'],
  File "/ysm-gpfs/apps/software/Python/3.5.1-foss-2016a/lib/python3.5/os.py", line 683, in __getitem__
    raise KeyError(key) from None
KeyError: 'HG19'

**Comment by davek44** [comment]
Sorry this is overtuned for my setup; I keep an environmental variable pointing to reference genome files. You should be able to dodge this by providing the genome FASTA file with -f. If it's still breaking on the default, just change it to something benign.

I may be overinterpreting your command, but you'll want to be very thoughtful using this program for CLIP-seq modeling. If you just provide large genome blocks like I do for DNase, ATAC, ChIP, and CAGE, you'll be asking the model to learn gene transcript definitions as well as the RNA binding protein sites. I expect that'll be too hard. That's why I focused on CAGE rather than RNA-seq for gene expression. You can provide smaller sequences and make the program behave more like Basset, but I haven't tested that thoroughly. I also haven't tested variable length sequences like you might want for RNA.

**Comment by kiranvpaul** [comment]
i have provided the fasta file using -f but still its breaking, I think i will change the default. Also i am actually looking for RBP binding sites from the CLIP data(as i dont have a CAGE data for this). So my plan was to preprocess the bam, train the sequences and predict motifs. Do you think this approach make sense??

**Comment by davek44** [comment]
It might work, but you'd likely fit much better models if it better understood the isoform structure of the genes. E.g. I would assemble the training set as RNA sequences annotated with the CLIP coverage or some transformation of it. But in that case, you have variable length sequences, and I don't think Basenji will work out of the box. Maybe you can choose a length that covers most genes and pad the shorter transcripts.
