### ISSUE TITLE
Release the processed data

### ISSUE THREAD

**Issue by ChongWu-Biostat** [calico/basenji#25]
I was very impressed by your paper, software and the tutorial. I found the pre-processing step is very tedious. I was wondering if you could release the processed data. By the way, do you compare the performance difference if we use processed data from the ENCODE and Roadmap directly? Thank you for your help!

**Comment by davek44** [comment]
I'm happy to share the data. My primary hesitation is that I've since improved the pre-processing (I initially compressed the high end of the CAGE data too much; it really doesn't have PCR duplicates) and moved to using TFRecords rather than HDF5 as a medium for input to the programs. But if it'll help get you started, here are some links to the data I studied in the paper:

https://storage.googleapis.com/131k/sample_wigs.txt
https://storage.googleapis.com/131k/l131k_w128.bed
https://storage.googleapis.com/131k/l131k_w128.h5

The HDF has keys like "train_in" and "train_out" that contain the one hot coded DNA sequence inputs and experimental dataset outputs that we want to predict. Similarly "valid_in/out" and "test_in/out". Open the HDF5 file and ask for the keys to see everything in there. The BED file describes the train/valid/test regions, and sample_wigs.txt describes the target datasets.
