### ISSUE TITLE
Predicting activity of sequences using model trained in the manuscript

### ISSUE THREAD

**Issue by aditiqamra** [calico/basenji#30]
Hi,

I am trying to use a custom bed file as input to predict the activity score in each genomic loci using the model trained and tested in the manuscript.

I was able to download the trained model from https://github.com/calico/basenji/tree/master/manuscript but I am not clear how to now use this model to make predictions on new sequences.

Also, if I want to run basenji_motifs.py on the same set of sequences, can you explain what does the data file - HDF5 file with test_in/test_out keys mean here ? I am getting confused with the "test_in/test_out keys" bit.

Thanks a lot- this is my first time implementing any neural network models and I appreciate your help !

**Comment by davek44** [comment]
Hi, I really haven't touched the basenji_motifs.py script in a long time. For my Basset codebase, it was initially useful to visualize the first layer filters, but I'm usually using max pools of width 2 now, which causes the first layer filters to usually learn pieces of motifs rather than full and interpretable motifs. So I'm not sure if it works or not. If it's very important to you to check out the filters, let me know, and I can spend some time with it.

If you have your sequences in BED format, then you can use basenji_predict_bed.py to make predictions. Right now, it's just making a prediction for the center 128 bp bin, but we could modify that if you want predictions across the whole sequence. (I just added that script to the repo, so pull the latest.)
